<?php
$controllers_build = '
<?php
/**
 * -------------------------------------------------------
 * Generated by Codekop - Code PHP Generator
 * Created on '.date('Y-m-d H:i:s').'
 * -------------------------------------------------------
 * 
 * @author       Codekop.com
 * @type         Codeigniter 3
 * @link         https://www.codekop.com/
 * @email        fauzancodekop@gmail.com / fauzan1892@codekop.com
 * @version      1.0.1
 * @copyright    (c) '.date('Y').'
 * 
 * File      : '.$class.'.php
 * Web Name  : Custom Your App Name
 * Developer : Custom Your Name
 * E-mail    : Custom Your Email
 * 
 * 
**/
defined("BASEPATH") OR exit("No direct script access allowed");
class '.$class.' extends CI_Controller {
	function __construct(){
	 	parent::__construct();
	}
    
    /* Display a listing of the resource. */
	public function index()
	{
		$this->data["title_web"] = "'.$class.'";
		$this->data["sidebar"] = "'.$table.'";
        $this->data["view_template"] = "contents/'.$baseurl.'/home";
        $this->data["'.$table.'"] = $this->db->query("SELECT * FROM '.$table.'")->result();
		$this->load->view("layouts/app",$this->data);
	}
    
    /* Show the form for creating a new resource. */
	public function create()
	{
		$this->data["title_web"] = "Create - '.$class.'";
		$this->data["sidebar"] = "'.$table.'";
        $this->data["view_template"] = "contents/'.$baseurl.'/create";
		$this->load->view("layouts/app",$this->data);
	}

    /* Show the form for editing or display the specified resource. */
    public function edit($id)
    {
        $cek = $this->db->get_where("'.$table.'",["id" => base64_decode($id)]);
        if($cek->num_rows() > 0){
            $edit = $cek->row();
            $this->data["edit"] = $edit;
            // $this->data["title_web"] = "Edit - '.$class.'";
            // $this->data["sidebar"] = "'.$table.'";
            // $this->data["view_template"] = "contents/'.$baseurl.'/edit";
            // $this->load->view("layouts/app",$this->data);
			$this->load->view("contents/'.$baseurl.'/edit",$this->data);
        }else{
            // echo "<br><h4 class=text-center> Data Not Found !</h4><br>";
            $this->session->set_flashdata("failed"," Data Not Found ! ");
            redirect(base_url("'.$baseurl.'"));
        }
    }
   ';