<?php
$controllers_build = '
<?php
/**
 * ------------------------------------------------------------------------
 * Generated by Codekop - Code PHP Generator 
 * @link https://www.codekop.com/
 * @author Fauzan Falah (fauzancodekop@gmail.com / fauzan1892@codekop.com)
 * Created on '.date('Y-m-d H:i:s').' - CodeIgniter 4.x
 * ------------------------------------------------------------------------
 * 
 * File      : '.$class.'.php
 * Web Name  : Custom Your App Name
 * Developer : Custom Your Name
 * E-mail    : Custom Your Email
 * 
 * 
**/
namespace App\Controllers;
use App\Models\R!@#'.$class.';

class '.$class.' extends BaseController
{
    protected $'.$table.';
 
    function __construct()
    {
        $this->'.$table.' = new '.$class.'_model();
    }

    /* Display a listing of the resource. */
	public function index()
	{
		$this->data["title_web"] = "'.$class.'";
		$this->data["sidebar"] = "'.$table.'";
        $this->data["view_template"] = "contents/'.$baseurl.'/home";
        $this->data["'.$table.'"] = $this->$'.$table.'->get'.$class.'()->findAll();
		view("layouts/app",$this->data);
	}
    
    /* Show the form for creating a new resource. */
	public function create()
	{
		$this->data["title_web"] = "Tambah - '.$class.'";
		$this->data["sidebar"] = "'.$table.'";
        $this->data["view_template"] = "contents/'.$baseurl.'/create";
		
        view("layouts/app",$this->data);
	}

    /* Show the form for editing or display the specified resource. */
    public function edit($id)
    {
        $edit = $this->'.$table.'->get'.$class.'(base64_decode($id))->getRow();
        if($edit){
            $this->data["edit"] = $edit;
            // $this->data["title_web"] = "Edit - '.$class.'";
            // $this->data["sidebar"] = "'.$table.'";
            // $this->data["view_template"] = "contents/'.$baseurl.'/edit";
            // view("layouts/app",$this->data);
			view("contents/'.$baseurl.'/edit",$this->data);
        }else{
            echo "<br><h4 class="text-center"> Data Not Found !</h4><br>";
            // $this->session->setFlashdata("failed"," Data Not Found ! ");
            // return redirect()->to(base_url("'.$baseurl.'"));
        }
    }
   ';

$controllers_build = preg_replace('/R!@#/i', '', $controllers_build);